// Module declarations for DevDash database sub-components
pub mod admin_catalog;
pub mod ai_assist;
pub mod app_storage;
pub mod audit;
pub mod autocomplete;
pub mod chart_formatter;
pub mod connection_catalog;
pub mod credentials;
pub mod csv_import;
pub mod ddl;
pub mod device_sync;
pub mod duckdb_engine;
pub mod encrypted_export;
pub mod executor;
pub mod export;
pub mod identifiers;
pub mod introspection;
pub mod json_tree;
pub mod diagnostics;
pub mod metrics_board;
pub mod migration_apply;
pub mod migrations_log;
pub mod paths;
pub mod pool;
pub mod profiler;
pub mod result_snapshots;
pub mod row_formatter;
pub mod safe_mode;
pub mod schema_migration;
pub mod shortcut_config;
pub mod ssh_tunnel;
pub mod staged_edits;
pub mod structure_editor;
pub mod transactions;
pub mod redis;
pub mod turso_engine;


